export const ADD_PLACE = "ADD_PLACE";
export const EDIT_PLACE = "EDIT_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";
export const LOAD_PLACES = "LOAD_PLACES";

export const ADD_SOC_INTERACTION = "ADD_SOC_INTERACTION";
export const EDIT_SOC_INTERACTION = "EDIT_SOC_INTERACTION";
export const DELETE_SOC_INTERACTION = "DELETE_SOC_INTERACTION";
export const LOAD_SOC_INTERACTIONS = "LOAD_SOC_INTERACTIONS";